INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "core_user" does not exist
LINE 1: ...user"."is_active", "core_user"."date_joined" FROM "core_user...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 230, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "core_user" does not exist
LINE 1: ...user"."is_active", "core_user"."date_joined" FROM "core_user...
                                                             ^
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/add/
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "status" violates not-null constraint
DETAIL:  Failing row contains (f, 2023-08-27 05:29:20.463876+00, 1, Begone, null, 2, 5, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1227, in save_model
    obj.save()
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: null value in column "status" violates not-null constraint
DETAIL:  Failing row contains (f, 2023-08-27 05:29:20.463876+00, 1, Begone, null, 2, 5, null).
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Commit has no field named 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py", line 18, in approve
    url = reverse('admin:approve_url', kwargs={'id': obj.id})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'approve_url' not found. 'approve_url' is not a valid view function or pattern name.
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Commit has no field named 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py", line 18, in approve
    url = reverse('admin:approve_url', kwargs={'id': obj.id})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'approve_url' not found. 'approve_url' is not a valid view function or pattern name.
ERROR:django.request:Internal Server Error: /admin/edit/commit/
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Commit has no field named 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/templatetags/admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 281, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py", line 18, in approve
    url = reverse('admin:approve_url', kwargs={'id': obj.id})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'approve_url' not found. 'approve_url' is not a valid view function or pattern name.
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/approve/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/approve/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
ERROR:django.request:Internal Server Error: /admin/edit/commit/approve/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
ERROR:django.request:Internal Server Error: /admin/edit/commit/approve/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/core/level/
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "core_level" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "core_level"
                                          ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/paginator.py", line 93, in count
    return c()
           ^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "core_level" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "core_level"
                                          ^
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/config/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/config/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/config/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/config/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/approve/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /admin/edit/commit/approve/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
ERROR:django.request:Internal Server Error: /admin/edit/commit/deny/2
Traceback (most recent call last):
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/reyaan/.local/share/virtualenvs/org-YHO1hpL3/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view edit.admin.method.__call__ didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/edit/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/core/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /admin/account/level/
WARNING:django.request:Not Found: /
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/account/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/wiki/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/wiki/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/reyaan/Projects/canadianhighschools/org/src/wiki/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
